# Generated by Django 4.2 on 2023-08-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_contact_number_customer_user_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_user_active',
            field=models.BooleanField(default=False),
        ),
    ]
