# Generated by Django 4.2 on 2023-04-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customeraddress'),
        ('store', '0003_product_price2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=10)),
                ('promo_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed Amount', 'Fixed Amount')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('started_at', models.DateField()),
                ('validity', models.DateField()),
                ('invoke', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Direct Bank Transfer', 'Direct Bank Transfer'), ('Pay on delivery', 'Pay on delivery')], max_length=200)),
                ('payment_status', models.CharField(choices=[('Not paid', 'Not paid'), ('Paid', 'Paid')], max_length=100)),
                ('paid_id', models.CharField(max_length=100)),
                ('payment_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promo_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_promo_applied', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Packaging', 'Packaging'), ('Shifted to Rider', 'Shifted to Rider'), ('Delivered', 'Delivered')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customeraddress')),
                ('order_processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.promo')),
            ],
        ),
    ]
