# Generated by Django 4.2 on 2023-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Direct Bank Transfer', 'Direct Bank Transfer'), ('Pay on delivery', 'Pay on delivery'), ('Pay on cash', 'Pay on cash')], max_length=200),
        ),
    ]
